# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
